version: '3'
services:
  app:
    image: jumpeimano/go-dep-image:1.11.4
    environment:
      GOPATH: /
    working_dir: /go/src/github.com/jumpeiMano/go-memcached
    volumes:
      - ../go-memcached:/go/src/github.com/jumpeiMano/go-memcached
    depends_on:
      - memcached_1
      - memcached_2
      - memcached_3
      - memcached_4
  memcached_1:
    image: memcached
    ports:
      - "11211:11211"
  memcached_2:
    image: memcached
    ports:
      - "11212:11211"
  memcached_3:
    image: memcached
    ports:
      - "11213:11211"
  memcached_4:
    image: memcached
    ports:
      - "11214:11211"
