version: 2.1
references:
  working_directory: &working_directory
                       ~/go-memcached
executors:
  builder:
    working_directory: *working_directory
    machine: true
  tester:
    working_directory: *working_directory
    docker:
      - image: golang:1.12
        environment:
          GO111MODULE: "on"
jobs:
  build:
    executor:
      name: builder
    steps:
      - checkout
      - run:
          name: docker build
          command: |
            docker-compose build
      - run:
          name: go mod download
          command: |
            make mod-download
      - run:
          name: lint
          command: |
            make lint
  test:
    executor:
      name: tester
    steps:
      - run:
          name: up
          command: |
            docker-compose up -d
      - run:
          name: Wait for memcached
          command: |
            make dockerize
      - run: make test

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
