version: 2.1
references:
  working_directory: &working_directory
                       ~/go-memcached
executors:
  builder:
    working_directory: *working_directory
    docker:
      - image: jumpeimano/go-dep-image:1.12
        environment:
          GO111MODULE: "on"
      - image: memcached
        command: ["-port", "11211"]
      - image: memcached
        command: ["-port", "11212"]
      - image: memcached
        command: ["-port", "11213"]
      - image: memcached
        command: ["-port", "11214"]
  linter:
    working_directory: *working_directory
    docker:
      - image: golangci/golangci-lint
        environment:
          GO111MODULE: "on"
jobs:
  build:
    executor:
      name: builder
    steps:
      - checkout
      - run:
          name: Wait for memcached
          command: |
            dockerize -wait tcp://localhost:11211 -timeout 1m
            dockerize -wait tcp://localhost:11212 -timeout 1m
            dockerize -wait tcp://localhost:11213 -timeout 1m
            dockerize -wait tcp://localhost:11214 -timeout 1m
      - run:
          name: test
          command: make test
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    executor:
      name: linter
    steps:
      - attach_workspace:
          at: .
      - run:
          name: lint
          command: golangci-lint run
workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - build
          filters:
            tags:
              only: /.*/
