version: 2.1
references:
  working_directory: &working_directory
                       ~/go-memcached
executors:
  builder:
    working_directory: *working_directory
    machine:
      docker_layer_caching: true
    environment:
      GOPATH: /home/circleci/.go_workspace
jobs:
  build:
    executor:
      name: builder
    steps:
      - checkout
      - run:
          name: docker build
          command: |
            docker-compose build
      - restore_cache:
          key: mod-cache-{{ checksum "go.sum" }}-v1?
      - run:
          name: go mod download
          command: |
            make mod-download
      - run:
          name: chown
          command: |
            sudo chown -R circleci:circleci ${GOPATH}/pkg/mod
      - save_cache:
          key: mod-cache-{{ checksum "go.sum" }}-v1?
          paths:
            - /home/circleci/.go_workspace/pkg/mod
      - run: make lint
      - run:
          name: Wait for memcached
          command: |
            dockerize -wait tcp://localhost:11211 -timeout 1m
            dockerize -wait tcp://localhost:11212 -timeout 1m
            dockerize -wait tcp://localhost:11213 -timeout 1m
            dockerize -wait tcp://localhost:11214 -timeout 1m
      - run: make test

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
