version: 2.1
references:
  working_directory: &working_directory
                       ~/go-memcached
executors:
  builder:
    working_directory: *working_directory
    docker:
      - image: golangci/golangci-lint:latest
        environment:
          GO111MODULE: "on"
      - image: memcached
        command: ["-port", "11211"]
      - image: memcached
        command: ["-port", "11212"]
      - image: memcached
        command: ["-port", "11213"]
      - image: memcached
        command: ["-port", "11214"]
jobs:
  build:
    executor:
      name: builder
    steps:
      - checkout
      - run:
          name: lint
          command: |
            golangci-lint run
      - run: make test

workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
