version: 2
references:
  build_config: &build_config
    working_directory: /go/src/github.com/jumpeiMano/go-memcached
    docker:
      - image: jumpeimano/go-dep-image:1.11
      - image: jumpeimano/memcached
      - image: jumpeimano/memcached
        command: ["-port", "11212"]
      - image: jumpeimano/memcached
        command: ["-port", "11213"]
      - image: jumpeimano/memcached
        command: ["-port", "11214"]
  restore_vendor_cache: &restore_vendor_cache
    restore_cache:
      key: vendor-cache-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
  save_vendor_cache: &save_vendor_cache
    save_cache:
      key: vendor-cache-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
      paths:
        - vendor
jobs:
  build:
    <<: *build_config
    steps:
      - run: go version
      - checkout
      - *restore_vendor_cache
      - run:
          name: Vendoring
          command: |
              if [ ! -e vendor ]; then
                  make dep-ensure
              fi
      - *save_vendor_cache
      - run: make lint
      - run:
          name: Wait for memcached
          command: |
            dockerize -wait tcp://localhost:11211 -timeout 1m
      - run: make test

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
